# Generated by Django 3.2.13 on 2022-05-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0393_realm_want_advertise_in_communities_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistrationuser',
            name='send_pm_to_referrer_on_signup',
            field=models.BooleanField(default=True),
        ),
    ]
